# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b0b8717bc7ff90b74af1d8b983550ecd33dbe4c9e822d11f43650f21c29959538f510cddc6f298e33d81b828cb3c31c004c80a7f73d86834b55bdff460d66bf

test:
  secret_key_base: 000b0861153aed34564ce47ba542245ba1222eb44a5ebb271822c6a2de58a96ae33fb9dc5695ba33ea5186e9977f8f1e1bd36ba9b456d774c1af85d68cd31f16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
